export enum CardItem {
	TYPE = 'نوع درخواست',
	DEPOSITE = ': ودیعه حداکثر',
	EJAREH = ': اجاره حداکثر',
	SIZE = ': متراژ حداقل',
	BEDROOM = ': اتاق خواب',
	LOCATION = ': محله',
	DESCRIPTION = ': توضیحات',
	AGE = ': سال ساخت',
	PARKING = ': توضیحات',
	ELEVATOR = ': توضیحات',
	WAREHOUSE = ': توضیحات',
	FAMILY = ': توضیحات',
	PET = ': توضیحات',
	FLOOR = ': توضیحات',
}
